# Includes complete Jenkins configuration in order to run Jenkins on Kubernetes
# To install run:
# helm install stable/jenkins --namespace jenkins --name jenkins -f ./jenkins-values.yam

Master:
  Image: "jenkinsci/jenkins"
  ImageTag: "lts"
  # No password for demonstration purposes
  UseSecurity: false
  Master.resources: {requests: {cpu: 50m, memory: 512Mi}, limits: {cpu: 2000m, memory: 2048Mi}}
  ServiceType: NodePort
  NodePort: 31111 

# List of plugins to be install during Jenkins master start
  InstallPlugins:
    - kubernetes:1.12.0
    - workflow-aggregator:2.5
    - workflow-job:2.23
    - git:3.9.1

Agent:
  Enabled: true

  # This container run the Jenkins Job. Instead of the default jenkinsci/jnlp-slave
  # it is replaced with a Jenkins Slave with Docker client and kubectl CLI abilities.
  Image: radumatei/jenkins-slave-docker
  ImageTag: kubectl
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock
    - type: HostPath
      hostPath: /root/.kube
      mountPath: /root/.kube

rbac:
  install: false
