apiVersion: v1
kind: Secret
metadata:
  name: quay
type: Opaque
data:
  username: am9uYXRoYW5fam9obnNvbityb2JvdA==
  password: NDk0V1ZEOVVWQ0c1Q1NWWFA4Q0ZUQTJLTFpLM1FaVjBCUDZISzM4WkZOUFlZRTBCUEFRVDRWVUlLUTRJRlBDUw==
